language: nodejs

before_script:
  - npm install

script: 
  - npm install
  - npx next build
  - npx next export -o gh-pages


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  
  on:
    branch: master